version: "3"

services:
  user-service:
    build: ./user-service
    ports:
      - "5001:5001"
    depends_on:
      - db
    networks:
      - app-network

  application-service:
    build: ./application-service
    ports:
      - "5000:5000"
    depends_on:
      - user-service
      - db
    networks:
      - app-network

  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=user_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./user-service/user/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    ports:
      - 27017:27017
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
